# Generated by Django 6.0 on 2025-12-03 20:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("time", models.TimeField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "city_or_site",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "paramotor_frame",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "paramotor_engine",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "wing_manufacturer",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("wing_model", models.CharField(blank=True, max_length=100, null=True)),
                ("wing_size", models.CharField(blank=True, max_length=50, null=True)),
                ("pilot", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "flight_altitude",
                    models.IntegerField(
                        blank=True, help_text="Altitude in meters", null=True
                    ),
                ),
                (
                    "flight_phase",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("takeoff", "Takeoff"),
                            ("landing", "Landing"),
                            ("flight", "Flight"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fatal", "Fatal"),
                            ("serious", "Serious"),
                            ("minor", "Minor"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "potentially_fatal",
                    models.BooleanField(
                        blank=True,
                        help_text="Could have resulted in death if it occurred at a different altitude / reserve did not deploy / pilot was less lucky",
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("causes_description", models.TextField(blank=True, null=True)),
                (
                    "reserve_use",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("not_deployed", "Not deployed"),
                            ("no_time", "Did not have time to open"),
                            ("tangled", "Became tangled"),
                            ("partially_opened", "Partially opened"),
                            ("fully_opened", "Fully opened"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "surface_type",
                    models.CharField(
                        blank=True,
                        help_text="water / forest / rocks / mountains / etc.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "cause_confidence",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("maximum", "Maximum — exactly determined what happened"),
                            ("high", "High — very likely identified what happened"),
                            (
                                "low",
                                "Low — not exactly known but plausible assumptions",
                            ),
                            ("minimal", "Minimal — nothing is clear"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "factor_low_altitude",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Low flight altitude"
                    ),
                ),
                (
                    "factor_maneuvers",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Performed maneuvers"
                    ),
                ),
                (
                    "factor_accelerator",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Accelerator position"
                    ),
                ),
                (
                    "factor_thermal_weather",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Thermally active weather"
                    ),
                ),
                (
                    "factor_rotor_turbulence",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Entered rotor turbulence"
                    ),
                ),
                (
                    "factor_trimmer_position",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Trimmer position"
                    ),
                ),
                (
                    "factor_reflex_profile",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Presence of reflex profile"
                    ),
                ),
                (
                    "factor_helmet_worn",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Helmet worn"
                    ),
                ),
                (
                    "factor_tree_collision",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Landed / collided with tree",
                    ),
                ),
                (
                    "factor_water_landing",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Landed / fell in water"
                    ),
                ),
                (
                    "source_links",
                    models.TextField(
                        blank=True,
                        help_text="Links to source / analysis (one per line)",
                        null=True,
                    ),
                ),
                (
                    "media_links",
                    models.TextField(
                        blank=True,
                        help_text="Videos / photos / reports (one per line)",
                        null=True,
                    ),
                ),
                (
                    "wind_speed",
                    models.CharField(
                        blank=True,
                        help_text="Wind speed / gusts",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("meteorological_conditions", models.TextField(blank=True, null=True)),
                ("thermal_conditions", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date", "-time"],
            },
        ),
    ]
