# Generated by Django 6.0 on 2025-12-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="title",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
