# Generated by Django 6.0 on 2025-12-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0002_incident_summary_incident_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="collapse_types",
            field=models.JSONField(
                blank=True,
                help_text="List of collapse types in sequence (e.g., ['asymmetric_medium', 'asymmetric_large', 'frontal', 'line_twist'])",
                null=True,
            ),
        ),
    ]
