# Generated by Django 6.0 on 2025-12-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0003_incident_collapse_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="paramotor_type",
            field=models.CharField(
                blank=True,
                choices=[("footlaunch", "Footlaunch"), ("trike", "Trike")],
                max_length=20,
                null=True,
            ),
        ),
    ]
