# Generated by Django 6.0 on 2025-12-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0004_incident_paramotor_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incident",
            name="factor_helmet_worn",
        ),
        migrations.AddField(
            model_name="incident",
            name="factor_helmet_missing",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Helmet missing"
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="factor_trimmer_position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("closed", "Closed"),
                    ("partially_open", "Partially open"),
                    ("fully_open", "Fully open"),
                ],
                max_length=20,
                null=True,
                verbose_name="Trimmer position",
            ),
        ),
    ]
