# Generated by Django 6.0 on 2025-12-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0005_remove_incident_factor_helmet_worn_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="factor_accelerator",
            field=models.CharField(
                blank=True,
                choices=[
                    ("released", "Released"),
                    ("partially_engaged", "Partially engaged"),
                    ("fully_engaged", "Fully engaged"),
                ],
                max_length=20,
                null=True,
                verbose_name="Accelerator position",
            ),
        ),
    ]
