# Generated by Django 6.0 on 2025-12-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0006_alter_incident_factor_accelerator"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="pilot_actions",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "wrong_input_triggered",
                        "Wrong input triggered incident / was primary reason",
                    ),
                    ("mostly_wrong", "Mostly wrong inputs while reacting on incident"),
                    ("mixed", "Some correct and some wrong inputs while reacting"),
                    (
                        "mostly_correct",
                        "Mostly correct inputs while reacting on incident",
                    ),
                ],
                max_length=30,
                null=True,
                verbose_name="Pilot actions",
            ),
        ),
    ]
