# Generated by Django 6.0 on 2025-12-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0007_incident_pilot_actions"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="injury_details",
            field=models.TextField(
                blank=True, help_text="Details of pilot injuries if any", null=True
            ),
        ),
    ]
