# Generated by Django 6.0 on 2025-12-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0008_incident_injury_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="bad_hardware_preflight",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Hardware issue could be found on preflight",
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="hardware_failure",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Hardware failure occurred"
            ),
        ),
    ]
