# Generated by Django 6.0 on 2025-12-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0009_incident_bad_hardware_preflight_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="factor_ground_starting",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Ground starting"
            ),
        ),
    ]
