# Generated by Django 6.0 on 2025-12-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0010_incident_factor_ground_starting"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="factor_powerline_collision",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Powerline collision"
            ),
        ),
    ]
