# Generated by Django 6.0 on 2025-12-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0011_incident_factor_powerline_collision"),
    ]

    operations = [
        migrations.RenameField(
            model_name="incident",
            old_name="pilot",
            new_name="pilot_details",
        ),
        migrations.AddField(
            model_name="incident",
            name="pilot_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
