# Generated by Django 6.0 on 2025-12-04 16:08

from django.db import migrations, models


def set_turbulent_conditions(apps, schema_editor):
    Incident = apps.get_model("incidents", "Incident")
    Incident.objects.filter(
        models.Q(factor_thermal_weather=True) | models.Q(factor_rotor_turbulence=True)
    ).update(factor_turbulent_conditions=True)


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0012_rename_pilot_incident_pilot_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="factor_turbulent_conditions",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Turbulent conditions"
            ),
        ),
        migrations.RunPython(set_turbulent_conditions, migrations.RunPython.noop),
    ]
