# Generated by Django 6.0 on 2025-12-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0013_factor_turbulent_conditions"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="report_raw",
            field=models.TextField(
                blank=True,
                help_text="Raw reports / analysis copied from source",
                null=True,
            ),
        ),
    ]
