# Generated by Django 6.0 on 2025-12-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0014_report_raw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="pilot_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="wind_speed",
            field=models.TextField(
                blank=True, help_text="Wind speed / gusts", null=True
            ),
        ),
    ]
