# Generated by Django 6.0 on 2025-12-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0015_alter_incident_pilot_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="factor_spiral_maneuver",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Spiral maneuver"
            ),
        ),
    ]
