# Generated by Django 6.0 on 2025-12-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0016_factor_spiral_maneuver"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="factor_mid_air_collision",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fly_nearby", "Fly nearby"),
                    ("got_in_wake_turbulence", "Got in wake turbulence"),
                    ("almost_collided", "Almost collided"),
                    ("collided", "Collided"),
                ],
                max_length=30,
                null=True,
                verbose_name="Mid-air collision",
            ),
        ),
    ]
