# Generated by Django 6.0 on 2025-12-07 15:34

from django.db import migrations, models


def mark_existing_as_verified(apps, schema_editor):
    Incident = apps.get_model("incidents", "Incident")
    Incident.objects.all().update(verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0017_factor_mid_air_collision"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="verified",
            field=models.BooleanField(
                default=False, help_text="Incident has been reviewed and verified"
            ),
        ),
        migrations.RunPython(mark_existing_as_verified, migrations.RunPython.noop),
    ]
