# Generated by Django 6.0 on 2025-12-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0018_add_verified_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="flight_phase",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ground", "Ground"),
                    ("takeoff", "Takeoff"),
                    ("landing", "Landing"),
                    ("flight", "Flight"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
