# Generated by Django 6.0 on 2025-12-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0019_alter_incident_flight_phase"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="wind_speed_ms",
            field=models.FloatField(
                blank=True, help_text="Wind speed in m/s", null=True
            ),
        ),
    ]
