# Generated by Django 6.0 on 2025-12-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0022_alter_incident_primary_cause"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="factor_wake_turbulence",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Wake turbulence"
            ),
        ),
    ]
