# Generated by Django 6.0 on 2025-12-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0023_incident_factor_wake_turbulence"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="factor_rain",
            field=models.BooleanField(blank=True, null=True, verbose_name="Rain"),
        ),
    ]
