# Generated by Django 6.0 on 2025-12-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0024_incident_factor_rain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="primary_cause",
            field=models.CharField(
                blank=True,
                choices=[
                    ("turbulence", "Turbulence"),
                    ("wrong_control_input", "Wrong control input"),
                    ("hardware_failure", "Hardware failure"),
                    ("powerline_collision", "Powerline collision / Near Miss"),
                    ("midair_collision", "Midair collision / Near Miss"),
                    (
                        "lines_brakes_issues",
                        "Lines & Brakes Knots / Twists / Obstructions",
                    ),
                    ("water_landing", "Water landing"),
                    ("preflight_error", "Preflight Error"),
                ],
                max_length=30,
                null=True,
                verbose_name="Primary cause",
            ),
        ),
    ]
