# Generated by Django 6.0 on 2025-12-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0027_add_ground_object_collision_primary_cause"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="factor_ground_object_collision",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Ground object collision"
            ),
        ),
    ]
