# Generated by Django 6.0 on 2025-12-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0030_alter_incident_factor_accelerator"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="original_uuid",
            field=models.UUIDField(
                blank=True,
                help_text="Reference to original document when editing draft",
                null=True,
            ),
        ),
    ]
