# Generated by Django 6.0 on 2025-12-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0032_add_rain_fog_snow_primary_cause"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="factor_released_brake_toggle",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Released / lost the brake toggle"
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="factor_wrongly_adjusted_trims",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Wrongly adjusted trims"
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="factor_accidental_motor_kill",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Accidental motor kill"
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="factor_wrong_throttle_management",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Wrong throttle management"
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="factor_accidental_reserve_deployment",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Accidental reserve deployment"
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="factor_oscillations_out_of_control",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Oscillations out of control"
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="factor_student_pilot",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Student pilot"
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="factor_medical_issues",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Had medical issues"
            ),
        ),
    ]
