# Generated by Django 6.0 on 2025-12-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0033_add_pilot_related_factors"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="factor_engine_failure",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Engine failure"
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="factor_trimmers_failure",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Trimmers failure"
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="factor_structural_failure",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Structural failure (frame / carabiners / etc.)"
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="factor_fire",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Fire"
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="factor_throttle_system_issues",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Throttle system issues (cable / button / etc.)"
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="factor_paraglider_failure",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Paraglider (wing) failure (material / porosity issues / torn / etc.)"
            ),
        ),
    ]
