# Generated by Django 6.0 on 2025-12-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0035_alter_incident_primary_cause"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="factor_gust_front",
            field=models.BooleanField(blank=True, null=True, verbose_name="Gust front"),
        ),
        migrations.AddField(
            model_name="incident",
            name="factor_wind_shear",
            field=models.BooleanField(blank=True, null=True, verbose_name="Wind shear"),
        ),
    ]
