# Generated by Django 6.0 on 2026-01-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0036_incident_factor_gust_front_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="factor_out_of_fuel",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Out of fuel"
            ),
        ),
    ]
